### ISSUE TITLE
UDP Scan without root cause exceptions

### ISSUE THREAD

**Issue by f-froehlich** [nmmapper/python3-nmap#34]
I'm running the code as the following:
`
nmap = nmap3.NmapScanTechniques()
report = nmap.nmap_udp_scan(HOST, '--top-ports 1000')
`

It cause the exception:
`
You requested a scan type which requires root privileges.
QUITTING!
Traceback (most recent call last):
  File "/home/fabian/.local/lib/python3.8/site-packages/nmap3/nmap3.py", line 261, in get_xml_et
    return ET.fromstring(command_output)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./check_open_ports.py", line 36, in <module>
    OpenPorts()
  File "/home/fabian/monitoring-utils/monitoring_utils/Checks/NMAP/OpenPorts.py", line 48, in __init__
    Plugin.__init__(self, 'Check DNSSEC status')
  File "/home/fabian/monitoring-utils/monitoring_utils/Core/Plugin/Plugin.py", line 51, in __init__
    self.run()
  File "/home/fabian/monitoring-utils/monitoring_utils/Checks/NMAP/OpenPorts.py", line 66, in run
    self.check_ports()
  File "/home/fabian/monitoring-utils/monitoring_utils/Checks/NMAP/OpenPorts.py", line 70, in check_ports
    report, report = self.__executor.scan()
  File "/home/fabian/monitoring-utils/monitoring_utils/Core/Executor/NMAPExecutor.py", line 62, in scan
    return self.scan_top_ports()
  File "/home/fabian/monitoring-utils/monitoring_utils/Core/Executor/NMAPExecutor.py", line 74, in scan_top_ports
    udp_host_result, udp_runtime, udp_stats = self.scan_udp()
  File "/home/fabian/monitoring-utils/monitoring_utils/Core/Executor/NMAPExecutor.py", line 112, in scan_udp
    report = nmap.nmap_udp_scan(self.__host, self.get_args())
  File "/home/fabian/.local/lib/python3.8/site-packages/nmap3/nmap3.py", line 369, in nmap_udp_scan
    xml_root = self.scan_command(self.udp_scan, target=target, args=args)
  File "/home/fabian/.local/lib/python3.8/site-packages/nmap3/nmap3.py", line 316, in scan_command
    xml_root = self.get_xml_et(output)
  File "/home/fabian/.local/lib/python3.8/site-packages/nmap3/nmap3.py", line 262, in get_xml_et
    except xml.etree.ElementTree.ParseError:
NameError: name 'xml' is not defined
`

First of all it cause because `Nmap.run_command()` does not check the command output for errors. I expect to get an exception or a valid json like

{
  'runtime': {
    'time': 'XX',
    'timestr': 'XX',
    'elapsed': 'XX',
    'summary': 'require root privileges',
    'exit': 'failure'
  },
  'stats': {
    'scanner': 'nmap',
    'args': '/usr/bin/nmap -oX - -sT --top-ports 1000 192.168.0.10',
    'start': 'XX',
    'startstr': 'XX',
    'version': 'XX',
    'xmloutputversion': 'XX'
  }
}

Furthermore xou don't check the output in `Nmap.scan_command()` If there was an regular error (like above) you should not parse the XML output. Also the exception handling in `Nmap.get_xml_et()` is wrong because `xml.etree.ElementTree.ParseError` sould be `ParseError` instead.

Best whishes

Fabian Fröhlich

**Comment by nmmapper** [comment]
Okay
