### ISSUE TITLE
Version detection not running with Python3.10

### ISSUE THREAD

**Issue by njmulsqb** [nmmapper/python3-nmap#82]
Hi,

I am trying to run version detection and vulners script on Python 3.10 but its failing for some reason
```
import nmap3

nmap = nmap3.Nmap()
result = nmap.nmap_version_detection('8.8.8.8',args="--script vulners --script-args mincvss+5.0" )
print(result)
```
and the error looks something like
```
Traceback (most recent call last):
  File "/home/cybersoldier/Documents/nmap.py", line 4, in <module>
    result = nmap.nmap_version_detection('8.8.8.8',args="--script vulners --script-args mincvss+5.0" ) #Add the -p- flag here, removed for testing purposes
  File "/usr/local/lib/python3.10/dist-packages/nmap3/nmap3.py", line 195, in nmap_version_detection
    xml_root = self.scan_command(target=target, arg=arg, args=args, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/nmap3/nmap3.py", line 125, in scan_command
    output = self.run_command(scan_shlex, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/nmap3/nmap3.py", line 264, in run_command
    raise NmapExecutionError('Error during command: "' + ' '.join(cmd) + '"\n\n' + errs.decode('utf8'))
nmap3.exceptions.NmapExecutionError: Error during command: "/usr/bin/nmap -oX - 8.8.8.8 -sV --script vulners --script-args mincvss+5.0"
```

I have tried running the script both with and without `sudo` but the error stays the same.

**Comment by nmmapper** [comment]
Let me check it out.

**Comment by njmulsqb** [comment]
Hi @nmmapper, have you checked this? Is this a valid issue?

**Comment by nmmapper** [comment]
For me in works perfectly on python 10 also.

Ensure that you have got nmap tool install on your machine 
`apt-get install nmap`

**Comment by nmmapper** [comment]
Closing this issue, if it's not working for you again, then you can re-open another issue
